### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by alexpreynolds** [johnaparker/h5tree#1]
I have an HDF5 container I'd like to investigate:

```
% h5debug hilbert_genome_cooler_data/bg2.signal.mcool 
Reading signature at address 0 (rel)
File Super Block...
File name (as opened):                             hilbert_genome_cooler_data/bg2.signal.mcool
File name (after resolving symlinks):              hilbert_genome_cooler_data/bg2.signal.mcool
File access flags                                  0x00000000
File open reference count:                         1
Address of super block:                            0 (abs)
Size of userblock:                                 0 bytes
Superblock version number:                         0
Free list version number:                          0
Root group symbol table entry version number:      0
Shared header version number:                      0
Size of file offsets (haddr_t type):               8 bytes
Size of file lengths (hsize_t type):               8 bytes
Symbol table leaf node 1/2 rank:                   4
Symbol table internal node 1/2 rank:               16
Indexed storage internal node 1/2 rank:            32
File status flags:                                 0x00
Superblock extension address:                      UNDEF (rel)
Shared object header message table address:        UNDEF (rel)
Shared object header message version number:       0
Number of shared object header message indexes:    0
Address of driver information block:               UNDEF (rel)
Root group symbol table entry:                     
   Name offset into private heap:                  0
   Object header address:                          96
   Cache info type:                                Symbol Table
   Cached entry information:                      
      B-tree address:                              136
      Heap address:                                680
```

When I try to investigate with `h5tree` I get a `FileNotFoundError` exception:

```
% h5tree -va "hilbert_genome_cooler_data/bg2.signal.mcool"      
Traceback (most recent call last):
  File "/Users/areynolds/miniconda3/envs/cooler/bin/h5tree", line 156, in <module>
    with h5py.File(filepath, 'r') as f:
  File "/Users/areynolds/miniconda3/envs/cooler/lib/python3.10/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Users/areynolds/miniconda3/envs/cooler/lib/python3.10/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'hi', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

The `name` property in the error looks a bit suspicious.

**Comment by 0xDBFB7** [comment]
This occurs when the file extension is not '.h5'; then `args.path.find(locater)` returns -1. As a cheap workaround you can rename the file to 'h5' or change the line to something like 

```
if(args.path.find(locater) == -1):                                                                                                                                                
    sep_index = len(args.path)                                                                                                                                                    
else:                                                                                                                                                                             
    sep_index = args.path.find(locater) + len(locater)                                                                                                                            
```  

It's not clear to me why the index of the extension is needed.

Thanks for the tool John Parker, gives a lot of info.
